<?php
/**
* @file
* A description of what your module does.
*/
/**
 * Implements hook_link_alter().
 */
function nfb_user_portal_menu_local_tasks_alter(&$data, $route_name) {
    if($route_name == 'user.pass'  && isset($data['tabs'][0])) {
        // Remove all tabs from user login form.
        foreach ($data['tabs'][0] as $key => $tab){
            $data['tabs'][0][$key]['#access'] = FALSE;
        }
    }
}
function nfb_user_portal_mail($key, &$message, &$params)
{

    switch ($key) {case 'nfb_user_portal_pass_wrod':
            $from = "web@nfb.org";
            \drupal::logger("params_check")->notice("params: ".print_r($params, true));
            $message['subject'] = $params['subject'];
            $message['body'][] =   Drupal\Core\Mail\MailFormatHelper::htmlToText($params['message']);
            $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
            break;
        case 'nfb_user_portal_u_name_1':
            $from = "web@nfb.org";
            $message['subject'] = $params['subject'];
            $message['body'][] =  Drupal\Core\Mail\MailFormatHelper::htmlToText($params['message']);
            $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
            break;
        case 'nfb_user_portal_complete':
            $form = "Web@nfb.org";
            $message['subject'] = $params['subject'];
            $message['body'][] =   Drupal\Core\Mail\MailFormatHelper::htmlToText($params['message']);
            $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
            break;
    }

}

