<?php
/**
* @file
* A description of what your module does.
*/
/**
 * Implements hook_link_alter().
 */
function nfb_user_portal_tasks_alter(&$data, $route_name) {
    // Remove the "Reset your password" tab only from the login page.
    if ($route_name == 'user.pass') {
        unset($data['tabs']['0']['user.login']);
    }
}
function nfb_user_portal_mail($key, &$message, &$params)
{

    switch ($key) {
        case 'nfb_user_portal_pass_wrod':
            $from = "web@nfb.org";
            \drupal::logger("params_check")->notice("params: ".print_r($params, true));
            $message['subject'] = $params['subject'];
            $message['body'][] =   Drupal\Core\Mail\MailFormatHelper::htmlToText($params['message']);
            $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
            break;
        case 'nfb_user_portal_u_name_1':
            $from = "web@nfb.org";
            $message['subject'] = $params['subject'];
            $message['body'][] =  Drupal\Core\Mail\MailFormatHelper::htmlToText($params['message']);
            $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
            break;
        case 'nfb_user_portal_complete':
            $form = "Web@nfb.org";
            $message['subject'] = $params['subject'];
            $message['body'][] =   Drupal\Core\Mail\MailFormatHelper::htmlToText($params['message']);
            $message['headers']['Content-Type'] = 'text/html; charset=UTF-8; format=flowed; delsp=yes';
            break;
    }

}